#! /usr/bin/env ruby

# Get is a toolbox based on git which simplifies the adoption of conventions and some git commands.
# Copyright (C) 2023  Alex Speranza

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program and the additional permissions granted by
# the Lesser GPL.  If not, see <https://www.gnu.org/licenses/>.

# frozen_string_literal: true

require 'json'
require 'open3'
require_relative './test_lib'

module TestMain
  extend TestLibrary

  TEST_BRANCHES = [
    'init/test-simple',
  ].freeze

  def self.main
    warn_and_exit 'This script must be run when in the root folder of Get' unless pwd_root_of_project?

    built_images(maintained_ruby_versions)
      .tap { |images| puts "Built images for ruby versions: #{images.join(', ')}" }
      .tap { |images| start_containers_from_images(images, TEST_BRANCHES) }
      .each { |i| remove_image(i) }
  end
end

TestMain.main
